
DROP SCHEMA IF EXISTS ds_master;
DROP SCHEMA IF EXISTS ds_slave_0;
DROP SCHEMA IF EXISTS ds_slave_1;

CREATE SCHEMA IF NOT EXISTS ds_master;
CREATE SCHEMA IF NOT EXISTS ds_slave_0;
CREATE SCHEMA IF NOT EXISTS ds_slave_1;

